### PR TITLE
Cross vendor mesh shading

### PR DESCRIPTION
**Pull request by asafran**
## Description

The VK_NV_mesh_shader extension associated with NVidia RTX hardware has been replaced with vendor neutral VK_EXT_mesh_shader

## Type of change

-  New feature
-  Breaking change

## How Has This Been Tested?

Run vsgmeshshader example from vsgExamples CrossVendorMeshShading branch 

**Test Configuration**:
* Fedora Linux 37
* KDE 5.27.2, Wayland
* Mesa 23.0
* Vulkan 1.3.239.0
* the latest vsgglslang
* spirv-tools 2023.1

Hardware:
* AMD RDNA2 RX 6400

### CODE REVIEW

**Comment by robertosfield** [comment]
I've enabled the automated builds but they fail, I presume due to an older VulkanSDK version.  The error is:

```
In file included from /home/runner/work/VulkanSceneGraph/VulkanSceneGraph/include/vsg/vk/Device.h:16:
/home/runner/work/VulkanSceneGraph/VulkanSceneGraph/include/vsg/vk/Extensions.h:51:9: error: unknown type name 'PFN_vkCmdDrawMeshTasksEXT'; did you mean 'PFN_vkCmdDrawMeshTasksNV'?
        PFN_vkCmdDrawMeshTasksEXT vkCmdDrawMeshTasksEXT = nullptr;
        ^~~~~~~~~~~~~~~~~~~~~~~~~
        PFN_vkCmdDrawMeshTasksNV
/opt/hostedtoolcache/ndk/r23c/x64/toolchains/llvm/prebuilt/linux-x86_64/sysroot/usr/include/vulkan/vulkan_core.h:9946:26: note: 'PFN_vkCmdDrawMeshTasksNV' declared here
typedef void (VKAPI_PTR *PFN_vkCmdDrawMeshTasksNV)(VkCommandBuffer commandBuffer, uint32_t taskCount, uint32_t firstTask);
                         ^
In file included from /home/runner/work/VulkanSceneGraph/VulkanSceneGraph/src/vsg/core/ConstVisitor.cpp:13:
In file included from /home/runner/work/VulkanSceneGraph/VulkanSceneGraph/include/vsg/all.h:50:
In file included from /home/runner/work/VulkanSceneGraph/VulkanSceneGraph/include/vsg/maths/sample.h:17:
In file included from /home/runner/work/VulkanSceneGraph/VulkanSceneGraph/include/vsg/state/Sampler.h:15:
In file included from /home/runner/work/VulkanSceneGraph/VulkanSceneGraph/include/vsg/vk/Device.h:16:
/home/runner/work/VulkanSceneGraph/VulkanSceneGraph/include/vsg/vk/Extensions.h:52:9: error: unknown type name 'PFN_vkCmdDrawMeshTasksIndirectEXT'; did you mean 'PFN_vkCmdDrawMeshTasksIndirectNV'?
        PFN_vkCmdDrawMeshTasksIndirectEXT vkCmdDrawMeshTasksIndirectEXT = nullptr;
        ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
        PFN_vkCmdDrawMeshTasksIndirectNV
/opt/hostedtoolcache/ndk/r23c/x64/toolchains/llvm/prebuilt/linux-x86_64/sysroot/usr/include/vulkan/vulkan_core.h:9947:26: note: 'PFN_vkCmdDrawMeshTasksIndirectNV' declared here
typedef void (VKAPI_PTR *PFN_vkCmdDrawMeshTasksIndirectNV)(VkCommandBuffer commandBuffer, VkBuffer buffer, VkDeviceSize offset, uint32_t drawCount, uint32_t stride);

```

My build worked fine with VulkanSDK 1.3.239.0, I'll try older SDKs to see if I can recreate the problem first hand. I have merged the PR as a branch: asafran-CrossVendorMeshShading so will have a bash at fixing the compile error on this branch once I can recreate it.

My AMD 5700G doesn't include support for VK_EXT_mesh_shader so I'll need to drop in my Geforce 2060 card and test the runtime side.

**Comment by asafran** [comment]
There was a problem with that the barycentric extension was released before the mesh shader extension. I fixed this by separating the definitions and defining the correct versions.

**Comment by robertosfield** [comment]
Thanks that fix works for my 1.2.135.0 build.

Now on to testing on my Geforce 2060 system.

**Comment by robertosfield** [comment]
I have installed my Geforce 2060 and tried VSG/vsgExample master and found that I don't see anything on screen now.  It's quite a while since I had my 2060 installed so don't know if this is a regression in the VSG or a driver issue.  

When I use the new mesh shader branch I get exception thrown "failed to create logical device".

When I run vsgmeshshaders with the new branch the following is written to the console:
```

$ vsgmeshshader 
mesh_features.meshShader = 1
mesh_features.taskShader = 1
barycentric_features.fragmentShaderBarycentric = 1
mesh_properites.maxTaskWorkGroupTotalCount = 65535
mesh_properites.maxMeshSharedMemorySize = 0
mesh_properites.maxMeshPayloadAndSharedMemorySize = 0
mesh_properites.maxMeshOutputMemorySize = 0
mesh_properites.maxMeshOutputVertices = 0
mesh_properites.maxMeshOutputPrimitives = 0
Using vsg::DrawMeshTasks
Error: vsg::Device::create(...) failed to create logical device. VkResult = -7

```

When I run vsgmeshshaders from VSG/vsgExamples master I see:
```
nv_features.meshShader = 1
nv_features.taskShader = 1
barycentric_features.fragmentShaderBarycentric = 1
mesh_properites.maxDrawMeshTasksCount = 65535
mesh_properites.maxTaskTotalMemorySize = 16384
mesh_properites.maxMeshTotalMemorySize = 16384
mesh_properites.maxMeshOutputVertices = 256
mesh_properites.maxMeshOutputPrimitives = 512
Using vsg::DrawMeshTasks

```

If I checked for extension support I just get a hit for the VK_NV_mesh_shader version:

$ vsgdeviceselection -e | grep mesh
    extensionName = VK_NV_mesh_shader, spec = 1

The driver looks to be NVIDIA 510.108.03.

I'll look into whether there are any new driver updates.

**Comment by robertosfield** [comment]
Updating the driver has added support forr VK_EXT_mesh_shader and the vsgmeshshader example now runs and produces two multi-colored triangles.

Screenshot_20230308_200745

Does this look correct?

When I run vsgmeshshaders with -d I don't get any Vulkan errors so this is encouraging.

**Comment by robertosfield** [comment]
Now I have a working example I'll move on to doing a proper code review, but it's end of day here so I'll tackle that tomorrow.

**Comment by robertosfield** [comment]
@asafran  I am currently doing my code review and have decided to change DrawMeshTasksIndirectCommand to use the same naming as the associated VkDrawMeshTasksIndirectCommandEXT rather than the x, y, z shorthand.  I also updated the vsgExamples branch to keep things compiling.

https://github.com/vsg-dev/VulkanSceneGraph/commit/73486a1ca0953ce59b1a8822e4909a1d70c631cc

The code in vsgmeshshaders example looks a bit awkward though so I'm now wondering whether it would be simpler to just use a uivec3Array,  I will change the code and see how it looks.

When I run vsgmeshshaders --type 0,  vsgmeshshaders --type 1, and vsgmeshshaders --type 2 everything works fine. but if I run vsgmeshshaders --type 3 I get a hang and lots of debug errors when I run with -d as well:

VUID-vkCmdDrawMeshTasksIndirectCountEXT-stride-07096(ERROR / SPEC): msgNum: -1946792588 - Validation Error: [ VUID-vkCmdDrawMeshTasksIndirectCountEXT-stride-07096 ] Object 0: h
andle = 0x563000ca0a00, type = VK_OBJECT_TYPE_COMMAND_BUFFER; | MessageID = 0x8bf64d74 | stride 8 is invalid or less than sizeof(VkDrawMeshTasksIndirectCommandEXT) 12. The Vulk
an spec states: stride must be a multiple of 4 and must be greater than or equal to sizeof(VkDrawMeshTasksIndirectCommandEXT) (https://vulkan.lunarg.com/doc/view/1.3.239.0/linu
x/1.3-extensions/vkspec.html#VUID-vkCmdDrawMeshTasksIndirectCountEXT-stride-07096)
    Objects: 1
        [0] 0x563000ca0a00, type: 6, name: NULL
VUID-vkCmdDrawMeshTasksIndirectCountEXT-stride-07096(ERROR / SPEC): msgNum: -1946792588 - Validation Error: [ VUID-vkCmdDrawMeshTasksIndirectCountEXT-stride-07096 ] Object 0: h
andle = 0x563000cbf380, type = VK_OBJECT_TYPE_COMMAND_BUFFER; | MessageID = 0x8bf64d74 | stride 8 is invalid or less than sizeof(VkDrawMeshTasksIndirectCommandEXT) 12. The Vulk
an spec states: stride must be a multiple of 4 and must be greater than or equal to sizeof(VkDrawMeshTasksIndirectCommandEXT) (https://vulkan.lunarg.com/doc/view/1.3.239.0/linu
x/1.3-extensions/vkspec.html#VUID-vkCmdDrawMeshTasksIndirectCountEXT-stride-07096)
    Objects: 1
        [0] 0x563000cbf380, type: 6, name: NULL

Do you see this issue?

**Comment by robertosfield** [comment]
I have successfully changed to using uivec3Value, this simplifies the application code a bit, though it hides the 1:1 mapping of the naming.  if we are to dynamically update the data then have access to the uvec3 members would be easier than using the DrawMeshTasksIndirectCommand struct.

```
diff --git a/examples/meshshaders/vsgmeshshader/vsgmeshshader.cpp b/examples/meshshaders/vsgmeshshader/vsgmeshshader.cpp
index 63bfd96..5fd4a7e 100644
--- a/examples/meshshaders/vsgmeshshader/vsgmeshshader.cpp
+++ b/examples/meshshaders/vsgmeshshader/vsgmeshshader.cpp
@@ -134,10 +134,14 @@ int main(int argc, char** argv)
         else if (type <= 2)
         {
             std::cout << "Using vsg::DrawMeshTasksIndirect" << std::endl;
+#if 0
             auto data = vsg::DrawMeshTasksIndirectCommandArray::create(1);
             data->at(0).groupCountX = 3;
             data->at(0).groupCountY = 1;
             data->at(0).groupCountZ = 1;
+#else
+            auto data = vsg::uivec3Value::create(3, 1, 1);
+#endif
             scenegraph->addChild(vsg::DrawMeshTasksIndirect::create(data, 1, 8));
         }
         else

```

**Comment by robertosfield** [comment]
The new PR is #745.  I'm now just waiting for the automated builds to complete.
